### ISSUE TITLE
Having six players on at the same time makes the game load slowly

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#25]
![image](https://user-images.githubusercontent.com/68207888/116825043-5583b280-ab5b-11eb-8384-1256adb84e8d.png)

**Comment by maitian352** [comment]
Removing one player makes it work again.

**Comment by definitely-nobody-is-here** [comment]
hmmm, is there any errors in the server or client logs?

**Comment by definitely-nobody-is-here** [comment]
Oops, I accidentally closed it!

**Comment by definitely-nobody-is-here** [comment]
Hmm, this is peculiar. It seems as if the server cannot send 6 hd image files until only five players are left.

**Comment by definitely-nobody-is-here** [comment]
Or, the drawMap() function is unable to draw the map with 6 players.

**Comment by The-God-coder** [comment]
@maitian352 are there and client or server logs of errors

**Comment by maitian352** [comment]
Huh. I have six players in the lobby, and it works just fine, except when I try to join another player the site just refuses to load.

**Comment by definitely-nobody-is-here** [comment]
Interesting. And no, @The-God-coder there were no errors on the client or server side.

**Comment by maitian352** [comment]
This is hard

**Comment by definitely-nobody-is-here** [comment]
yes... I'm suspecting that the server is overloaded by the requests to load all six maps at once since each client separately loads a map

**Comment by maitian352** [comment]
I got 8 players connected by opening 8 tabs but not clicking log in, and 6 of them display the map while the other two dont.

**Comment by maitian352** [comment]
Wait, now all 8 work

**Comment by maitian352** [comment]
Now there is an error

```C:\Users\gu\Documents\BattleBoxes_Multiplayer\server\game.js:40
        localplayer.respawn(MAPS[CURRENT_MAP].spawns[j].x, MAPS[CURRENT_MAP].spawns[j].y);
                                                        ^

TypeError: Cannot read property 'x' of undefined
    at startRound (C:\Users\gu\Documents\BattleBoxes_Multiplayer\server\game.js:40:57)
    at Timeout._onTimeout (C:\Users\gu\Documents\BattleBoxes_Multiplayer\server\game.js:63:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)```

**Comment by definitely-nobody-is-here** [comment]
interesting. Oh, it ran out of spawnpoints! There are only 8 spawnpoints per map and so when more than 8 people join, it overflows and spits out an error.

**Comment by definitely-nobody-is-here** [comment]
And it seems like the clients are unable to load the map when the server is running behind from all those requests for maps and data.

**Comment by The-God-coder** [comment]
i still can't understand why drawMap isn't drawing

**Comment by maitian352** [comment]
Why do you think it is six players? Why not 5? Is it the map size?

**Comment by definitely-nobody-is-here** [comment]
probably.

**Comment by definitely-nobody-is-here** [comment]
It appears that the server IS overloaded with the requests for images.
![image](https://user-images.githubusercontent.com/67865358/117080960-ddf58500-ad0c-11eb-9709-bcccb0db2df9.png)
At the top the error is that the server sent an undefined map id, and then a bunch of connection refused errors follow. After waiting a few seconds the map WILL load.
![image](https://user-images.githubusercontent.com/67865358/117081052-1a28e580-ad0d-11eb-9c3f-8fddcac2b5ea.png)
However it is very laggy to switch tabs because the GPU is pegged at 100% use trying to render all of those pixels.
![image](https://user-images.githubusercontent.com/67865358/117081279-93283d00-ad0d-11eb-8819-d4f781eedbb9.png)
![image](https://user-images.githubusercontent.com/67865358/117081232-7db31300-ad0d-11eb-851a-c0dd5d31fa62.png)
The server is struggling to send the map files. In fact, it was so bad that it disconnected some of the players.
Those players would then reconnect and then get disconnected again.
![image](https://user-images.githubusercontent.com/67865358/117081515-08940d80-ad0e-11eb-9b12-58a0acda941d.png)

**Comment by definitely-nobody-is-here** [comment]
A possible solution is to compress the files by using 1x1 "blocks" instead of 40x40 "blocks". Another strategy is to load all the maps when joining the game and then load from cache instead of overloading the server all at once. By spreading the load of loading the map images the stress on the server can be reduced.

**Comment by The-God-coder** [comment]
@definitely-nobody-is-here We can save them in cookies...

**Comment by definitely-nobody-is-here** [comment]
The code has been modified to be able to load maps when more than five players are on. However the new limit is 7 players.

**Comment by definitely-nobody-is-here** [comment]
There are no errors saying connection denied but the page is slow to load, indicating server stress preventing images from loading fast enough.

**Comment by definitely-nobody-is-here** [comment]
This issue has been mostly fixed. Further fixes will be made to further reduce this issue.

**Comment by maitian352** [comment]
Why can't the client load the maps?

**Comment by definitely-nobody-is-here** [comment]
The client loads all the maps when they go click the player button and so it doesn't have to repeatedly request for maps every round.

**Comment by The-God-coder** [comment]
@definitely-nobody-is-here do the maps have to be served from the server they could be server from google drive or some other service to reduce load on the server

**Comment by definitely-nobody-is-here** [comment]
In fact they do, reducing load on the server by using google drive or github will make the loading slower and will also make development harder as it takes a while for those resources to update when using web storage.

**Comment by definitely-nobody-is-here** [comment]
Should we close this issue?

**Comment by definitely-nobody-is-here** [comment]
Okay, this issue is technically not a problem anymore so we can close this issue.

**Comment by maitian352** [comment]
why does madow garuder not have this problem
