### ISSUE TITLE
SUGGESTION - Add the ability to play multiple games on one server

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#70]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when someone presses ready with another player online and I can't play on the server.

**Describe the solution you'd like**
Anyone else will join the lobby and will be able to play in a different game. Chat messages will be global across the server.

**Describe alternatives you've considered**
Run multiple servers, however bad.

**Additional context**
*insert context here*

**Comment by definitely-nobody-is-here** [comment]
This might impact performance negatively if there are too many games running and it will require a rewrite of code in multiple different places. But might try.

**Comment by definitely-nobody-is-here** [comment]
Most games do search for a different server if a server is not available to keep simplicity.

**Comment by definitely-nobody-is-here** [comment]
Looking at how JavaScript works, it will be more resource-efficient to run multiple servers than to run multiple games on one server, since it is a single-threaded language. So instead of having multiple low-TPS games on one server it would be better to run multiple servers.

In short, no, this will not be added.
